import Link from "next/link";
import { ArrowRight, MailCheck, MessageSquareReply, Users } from "lucide-react";
import { LeadsTable } from "@/components/leads-table";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getContacts, getFollowUps, getMetrics } from "@/lib/data";
import { getViewer } from "@/lib/viewer";

export default async function DashboardPage() {
  const viewer = (await getViewer())!;
  const [metrics, contacts, followUps] = await Promise.all([getMetrics(viewer.id), getContacts(viewer.id), getFollowUps(viewer.id)]);
  const cards = [{ label: "Total leads", value: metrics.leads, icon: Users }, { label: "Emails sent", value: metrics.sent, icon: MailCheck }, { label: "Replies logged", value: metrics.replies, icon: MessageSquareReply }];
  return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.16em] text-primary">Friday, June 20</p><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Good morning, {viewer.name.split(" ")[0]}</h1><p className="mt-2 text-sm text-muted-foreground">Here’s the signal from your outreach today.</p></div><Button asChild><Link href="/app/leads">Add or import leads <ArrowRight className="size-4" /></Link></Button></div><section className="grid gap-4 sm:grid-cols-3">{cards.map(({ label, value, icon: Icon }) => <Card key={label}><CardContent className="flex items-start justify-between p-5"><div><p className="text-sm font-medium text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight">{value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-[#ffe6e2] text-primary"><Icon className="size-5" /></span></CardContent></Card>)}</section><section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Card className="min-w-0"><CardHeader className="flex-row items-center justify-between"><CardTitle>Recent leads</CardTitle><Button variant="ghost" size="sm" asChild><Link href="/app/leads">View all</Link></Button></CardHeader><CardContent className="px-0"><LeadsTable contacts={contacts.slice(0, 4)} compact /></CardContent></Card><Card><CardHeader><CardTitle>Today’s follow-ups</CardTitle></CardHeader><CardContent className="space-y-3">{followUps.length === 0 ? <p className="rounded-lg bg-muted p-4 text-sm text-muted-foreground">No follow-ups due today.</p> : followUps.map((item) => <Link key={item.id} href={`/app/leads/${item.contact_id}`} className="group block rounded-xl border p-4 transition-colors hover:border-[#f5a399] hover:bg-[#fff9f7]"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{item.contact_name}</p><p className="mt-1 text-xs text-muted-foreground">{item.company} · {new Date(item.follow_up_due).toLocaleTimeString("en", { hour: "numeric", minute: "2-digit" })}</p><p className="mt-3 line-clamp-1 text-sm text-muted-foreground">{item.subject}</p></div><ArrowRight className="mt-1 size-4 text-muted-foreground transition-transform group-hover:translate-x-1 group-hover:text-primary" /></div></Link>)}</CardContent></Card></section></div>;
}
