"use client";
import { useRef, useState } from "react";
import { FileUp, Plus } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export function AddLeadDialog() {
  const router = useRouter(); const fileRef = useRef<HTMLInputElement>(null);
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/leads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json(); setBusy(false); if (!response.ok) return setMessage(result.error); setOpen(false); router.refresh(); }
  async function importCsv(file?: File) { if (!file) return; setBusy(true); const text = await file.text(); const [header, ...lines] = text.trim().split(/\r?\n/); const keys = header.split(",").map((key) => key.trim().toLowerCase()); const leads = lines.map((line) => { const values = line.split(",").map((value) => value.trim()); return Object.fromEntries(keys.map((key, index) => [key, values[index] ?? ""])); }); const response = await fetch("/api/leads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(leads) }); const result = await response.json(); setBusy(false); setMessage(response.ok ? `${result.created} leads imported.` : result.error); if (response.ok) router.refresh(); }
  return <div className="flex gap-2"><input ref={fileRef} className="hidden" type="file" accept=".csv,text/csv" onChange={(event) => importCsv(event.target.files?.[0])} /><Button variant="outline" onClick={() => fileRef.current?.click()} disabled={busy}><FileUp className="size-4" /> <span className="hidden sm:inline">Import CSV</span></Button><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus className="size-4" /> Add lead</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add a new lead</DialogTitle><DialogDescription>Add only the context you know. AI drafts will stay grounded in these details.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label htmlFor="first_name">First name</Label><Input id="first_name" name="first_name" required /></div><div className="space-y-1.5"><Label htmlFor="last_name">Last name</Label><Input id="last_name" name="last_name" /></div><div className="space-y-1.5 sm:col-span-2"><Label htmlFor="email">Work email</Label><Input id="email" name="email" type="email" required /></div><div className="space-y-1.5"><Label htmlFor="company">Company</Label><Input id="company" name="company" required /></div><div className="space-y-1.5"><Label htmlFor="job_title">Role</Label><Input id="job_title" name="job_title" /></div><div className="space-y-1.5 sm:col-span-2"><Label htmlFor="notes">Notes</Label><Textarea id="notes" name="notes" placeholder="Why this person might be a fit…" /></div>{message && <p className="text-sm text-primary sm:col-span-2">{message}</p>}<div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? "Saving…" : "Save lead"}</Button></div></form></DialogContent></Dialog></div>;
}
