"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { signIn } from "next-auth/react";
import { Flame } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export function AuthForm({ mode }: { mode: "login" | "signup" }) { const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const signup = mode === "signup"; async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget)); if (signup) { const response = await fetch("/api/signup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) { setBusy(false); return setError(result.error); } } const result = await signIn("credentials", { email: data.email, password: data.password, redirect: false }); setBusy(false); if (result?.error) return setError("Email or password is incorrect."); router.push("/app"); router.refresh(); } return <div className="w-full max-w-md"><div className="mb-8 flex items-center gap-2 font-semibold lg:hidden"><Flame className="size-5 text-primary" />TheHotspot AI</div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">{signup ? "Start focused" : "Welcome back"}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">{signup ? "Create your workspace" : "Sign in to your workspace"}</h2><p className="mt-2 text-sm text-muted-foreground">{signup ? "Add your first lead and send a personal email in minutes." : "Your leads and follow-ups are waiting."}</p><Button type="button" variant="outline" className="mt-8 w-full" onClick={() => signIn("google", { callbackUrl: "/app" })}>Continue with Google</Button><div className="my-5 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border" />or use email<span className="h-px flex-1 bg-border" /></div><form onSubmit={submit} className="space-y-4">{signup && <div className="space-y-1.5"><Label htmlFor="name">Name</Label><Input id="name" name="name" autoComplete="name" required /></div>}<div className="space-y-1.5"><Label htmlFor="email">Email</Label><Input id="email" name="email" type="email" autoComplete="email" required /></div><div className="space-y-1.5"><Label htmlFor="password">Password</Label><Input id="password" name="password" type="password" autoComplete={signup ? "new-password" : "current-password"} minLength={8} required /></div>{error && <p className="text-sm text-primary" role="alert">{error}</p>}<Button className="w-full" disabled={busy}>{busy ? "Please wait…" : signup ? "Create account" : "Sign in"}</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">{signup ? "Already have an account?" : "New to TheHotspot?"} <Link className="font-semibold text-foreground hover:text-primary" href={signup ? "/login" : "/signup"}>{signup ? "Sign in" : "Create an account"}</Link></p></div>; }
