"use client";
import { useState } from "react";
import { Mail, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export function EmailWorkspace({ leadId, firstName }: { leadId: string; firstName: string }) {
  const [subject, setSubject] = useState(""); const [body, setBody] = useState(""); const [days, setDays] = useState(3); const [busy, setBusy] = useState<"generate" | "send" | null>(null); const [message, setMessage] = useState("");
  async function generate() { setBusy("generate"); setMessage(""); const response = await fetch(`/api/leads/${leadId}/generate-email`, { method: "POST" }); const result = await response.json(); setBusy(null); if (!response.ok) return setMessage(result.error); setSubject(result.subject); setBody(result.body); }
  async function send() { setBusy("send"); setMessage(""); const response = await fetch(`/api/leads/${leadId}/send-email`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject, body, followUpDays: days }) }); const result = await response.json(); setBusy(null); setMessage(response.ok ? result.demo ? "Demo send complete — no email left your account." : "Email sent with Gmail." : result.error); }
  return <div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-semibold">Email {firstName}</h2><p className="mt-1 text-sm text-muted-foreground">Generate a grounded draft, then make it yours.</p></div><Button variant="outline" onClick={generate} disabled={!!busy}><Sparkles className="size-4 text-primary" />{busy === "generate" ? "Drafting…" : "Generate with AI"}</Button></div><div className="space-y-1.5"><Label htmlFor="subject">Subject</Label><Input id="subject" value={subject} onChange={(event) => setSubject(event.target.value)} placeholder="A clear reason to open" /></div><div className="space-y-1.5"><Label htmlFor="body">Message</Label><Textarea id="body" value={body} onChange={(event) => setBody(event.target.value)} className="min-h-64 leading-6" placeholder={`Hi ${firstName},\n\nWrite a personal message or generate a starting point…`} /></div><div className="flex flex-col justify-between gap-4 border-t pt-5 sm:flex-row sm:items-end"><div className="space-y-1.5"><Label htmlFor="follow-up">Follow up after</Label><select id="follow-up" value={days} onChange={(event) => setDays(Number(event.target.value))} className="h-10 rounded-lg border bg-card px-3 text-sm"><option value={2}>2 days</option><option value={3}>3 days</option><option value={5}>5 days</option><option value={7}>7 days</option></select></div><Button onClick={send} disabled={!!busy || !subject || body.length < 20}><Mail className="size-4" />{busy === "send" ? "Sending…" : "Send with Gmail"}</Button></div>{message && <p className="rounded-lg bg-muted px-3 py-2 text-sm text-muted-foreground" role="status">{message}</p>}</div>;
}
