import Link from "next/link";
import { ArrowLeft, Building2, Mail, UserRound } from "lucide-react";
import { notFound } from "next/navigation";
import { EmailWorkspace } from "@/components/email-workspace";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getContact } from "@/lib/data";
import { initials } from "@/lib/utils";
import { getViewer } from "@/lib/viewer";

export default async function LeadPage({ params }: { params: Promise<{ id: string }> }) {
  const viewer = (await getViewer())!; const { id } = await params; const contact = await getContact(viewer.id, id); if (!contact) notFound();
  return <div className="space-y-6"><Button variant="ghost" size="sm" asChild className="-ml-3"><Link href="/app/leads"><ArrowLeft className="size-4" />Back to leads</Link></Button><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-2xl bg-[#ffe6e2] font-semibold text-primary">{initials(`${contact.first_name} ${contact.last_name}`)}</span><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">{contact.first_name} {contact.last_name}</h1><StatusBadge status={contact.status} /></div><p className="mt-1 text-sm text-muted-foreground">{contact.job_title} at {contact.company}</p></div></div></div><div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]"><div className="space-y-5"><Card><CardHeader><CardTitle>Lead details</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div className="flex gap-3"><Mail className="mt-0.5 size-4 text-muted-foreground" /><div><p className="text-xs text-muted-foreground">Email</p><p className="mt-0.5 font-medium break-all">{contact.email}</p></div></div><div className="flex gap-3"><Building2 className="mt-0.5 size-4 text-muted-foreground" /><div><p className="text-xs text-muted-foreground">Company</p><p className="mt-0.5 font-medium">{contact.company}</p></div></div><div className="flex gap-3"><UserRound className="mt-0.5 size-4 text-muted-foreground" /><div><p className="text-xs text-muted-foreground">Role</p><p className="mt-0.5 font-medium">{contact.job_title || "Not provided"}</p></div></div></CardContent></Card><Card><CardHeader><CardTitle>Context for AI</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">{contact.notes || "No notes yet. Add specific context before generating an email."}</p></CardContent></Card><Card><CardHeader><CardTitle>Outreach timeline</CardTitle></CardHeader><CardContent><div className="flex gap-3"><span className="mt-1.5 size-2 rounded-full bg-primary ring-4 ring-[#ffe6e2]" /><div><p className="text-sm font-medium">Lead added</p><p className="mt-1 text-xs text-muted-foreground">{new Date(contact.created_at).toLocaleDateString("en", { month: "long", day: "numeric", year: "numeric" })}</p></div></div></CardContent></Card></div><Card><CardContent className="p-5 sm:p-6"><EmailWorkspace leadId={contact.id} firstName={contact.first_name} /></CardContent></Card></div></div>;
}
